# --------------- Plugins ---------------

# plugins: replaygain duplicates missing fetchart embedart lastgenre chroma web scrub
plugins: duplicates missing fetchart embedart lastgenre chroma web scrub
directory: /music
# --------------- Main ---------------

library: /config/musiclibrary.blb
art_filename: albumart

# --------------- Performance ---------------

threaded: yes
original_date: no

# --------------- Tagging ---------------

per_disc_numbering: no

paths:
  default: $albumartist/$album ($year)/$track - $title
  singleton: Singles/$artist - $title
  comp: Compilations/$album ($year)/$track - $title
  albumtype_soundtrack: Soundtracks/$album ($year)/$track - $title

import:
  write: yes
  copy: no
  move: no
  incremental: no
  # incremental: yes
  quiet: no
  # quiet: yes
  quiet_fallback: skip
  resume: no
  # resume: yes

match:
  preferred:
    countries: [GB, US]
    media: [CD, Digital Media]

lastgenre:
  auto: yes
  source: album
  whitelist: yes
  min_weight: 10
  count: 3
  fallback:
  canonical: yes
  cleanup_existing: no
  force: no
  keep_existing: no
  prefer_specific: yes
  title_case: yes
  pretend: no
  ignorelist: {}
  aliases: yes

duplicates:
  count: yes
  checksum: yes

embedart:
  auto: yes
  maxwidth: 0
  compare_threshold: 0
  ifempty: no
  remove_art_file: no
  quality: 0
  clearart_on_import: no

fetchart:
  auto: yes
  fetch_for_asis: no
  minwidth: 0
  maxwidth: 0
  quality: 0
  max_filesize: 0
  enforce_ratio: no
  cautious: no
  cover_names:
  - cover
  - front
  - art
  - album
  - folder
  fallback:
  sources:
  - filesystem
  - coverart
  - itunes
  - amazon
  - albumart
  - cover_art_url
  store_source: no
  high_resolution: yes
  deinterlace: no
  cover_format:
  lastfm_key: REDACTED
  fanarttv_key: REDACTED
  google_key: REDACTED
  google_engine: REDACTED

scrub:
  auto: yes

replace:
  ^\.: _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '[\xE8-\xEB]': e
  '[\xEC-\xEF]': i
  '[\xE2-\xE6]': a
  '[\xF2-\xF6]': o
  '[\xF8]': o
  \.$: _
  \s+$: ''

web:
  host: 0.0.0.0
  port: 8337
  cors: ''
  cors_supports_credentials: no
  reverse_proxy: no
  include_paths: no
  readonly: yes

disabled_plugins: []

chroma:
  search_limit: 5
  data_source_mismatch_penalty: 0.5
  auto: yes