---
- name: Restart Docker
  systemd:
    name: docker
    state: restarted

- name: Restart media stack
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /srv/docker/media-stack
  changed_when: true