---
- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted

- name: Restart Docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted

- name: Deploy media stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    files:
      - docker-compose.yml
    state: present
    pull: missing