---
- name: Create QBittorrent configuration directory
  ansible.builtin.file:
    path: "{{ qbittorrent_config_path }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"

- name: Create QBittorrent namespace manifest
  ansible.builtin.template:
    src: qbittorrent-namespace.yaml.j2
    dest: /tmp/qbittorrent-namespace.yaml

- name: Create QBittorrent deployment manifest
  ansible.builtin.template:
    src: qbittorrent-deployment.yaml.j2
    dest: /tmp/qbittorrent-deployment.yaml

- name: Create QBittorrent service manifest
  ansible.builtin.template:
    src: qbittorrent-service.yaml.j2
    dest: /tmp/qbittorrent-service.yaml

- name: Deploy QBittorrent namespace
  kubernetes.core.k8s:
    state: present
    src: /tmp/qbittorrent-namespace.yaml
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy QBittorrent
  kubernetes.core.k8s:
    state: present
    src: /tmp/qbittorrent-deployment.yaml
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy QBittorrent Service
  kubernetes.core.k8s:
    state: present
    src: /tmp/qbittorrent-service.yaml
    kubeconfig: "{{ kubeconfig_path }}"