---
- name: Verify rancher filesystem exists
  ansible.builtin.command:
    cmd: findmnt /var/lib/rancher
  changed_when: false

- name: Verify containerd filesystem exists
  ansible.builtin.command:
    cmd: findmnt /var/lib/containerd
  changed_when: false

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: "{{ k3s_packages }}"
    state: present
    update_cache: true

- name: Create K3s configuration directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Create K3s configuration
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/config.yaml
    mode: "0644"
    content: |
      write-kubeconfig-mode: "{{ k3s_write_kubeconfig_mode }}"
      disable:
      {% for item in k3s_disable %}
        - {{ item }}
      {% endfor %}
      node-label:
      {% for item in k3s_node_labels %}
        - {{ item }}
      {% endfor %}

- name: Check if K3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install latest K3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    executable: /bin/bash
  when: not k3s_installed.stat.exists

- name: Enable K3s
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    state: started

- name: Wait for node to register
  ansible.builtin.command:
    cmd: kubectl get nodes
  register: k3s_ready
  retries: 30
  delay: 10
  until: k3s_ready.rc == 0
  changed_when: false

- name: Get node status
  ansible.builtin.command:
    cmd: kubectl get nodes -o wide
  register: kubectl_nodes
  changed_when: false

- name: Display node status
  ansible.builtin.debug:
    var: kubectl_nodes.stdout_lines