---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  apt:
    upgrade: dist

- name: Remove obsolete packages
  apt:
    autoremove: true

- name: Install common packages
  apt:
    name:
      - unzip
      - net-tools
      - fail2ban
      - dnsutils
      - python3-pip
      - rsync
      - tree
      - smartmontools
      - i965-va-driver
      - vainfo
      - intel-gpu-tools
      - nfs-common
      - vsftpd
    state: present

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: linuxadmin
    group: linuxadmin
    mode: "0755"
  loop: "{{ directories }}"

- name: Remove Directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ remove_directories }}"

- name: Configure sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ sysctl_settings }}"