---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade installed packages
  apt:
    upgrade: dist

- name: Remove obsolete packages
  apt:
    autoremove: true

- name: Install common packages
  apt:
    name:
      - unzip
      - net-tools
      - fail2ban
      - dnsutils
      - python3-pip
      - rsync
      - tree
      - smartmontools
      - i965-va-driver
      - vainfo
      - intel-gpu-tools
      - nfs-common
    state: present

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: linuxadmin
    group: linuxadmin
    mode: "0755"
  loop: "{{ directories }}"

# - name: Create Grafana data directory
#   ansible.builtin.file:
#     path: /srv/appdata/grafana/data
#     state: directory
#     owner: "{{ grafana_uid }}"
#     group: "{{ grafana_gid }}"
#     mode: "0755"

# - name: Create Node-RED data directory and correct existing permissions
#   ansible.builtin.file:
#     path: /srv/appdata/nodered
#     state: directory
#     owner: "{{ nodered_uid }}"
#     group: "{{ nodered_gid }}"
#     mode: "0750"
#     recurse: true

- name: Configure sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop: "{{ sysctl_settings }}"

# - name: Create Docker stack directory
#   file:
#     path: "{{ docker_compose_dir }}"
#     state: directory
#     owner: root
#     group: root
#     mode: "0755"

# - name: Install Python Kubernetes dependencies
#   apt:
#     name:
      
#     state: present

# - name: Install unattended upgrades
#   apt:
#     name:

#     state: present

# - name: Enable unattended upgrades
#   copy:
#     dest: /etc/apt/apt.conf.d/20auto-upgrades
#     owner: root
#     group: root
#     mode: "0644"
#     content: |
#       APT::Periodic::Update-Package-Lists "1";
#       APT::Periodic::Unattended-Upgrade "1";

# - name: Ensure unattended-upgrades service is enabled
#   service:
#     name: unattended-upgrades
#     enabled: true
#     state: started

# - name: Ensure fail2ban is enabled
#   service:
#     name: fail2ban
#     enabled: true
#     state: started