---
- name: Configure all servers
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  serial: 10%
  max_fail_percentage: 40

  roles:
    - role: common
      tags:
        - common
    
    - role: docker
      tags:
        - docker
