---
- name: Configure all servers
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  serial: 10%
  max_fail_percentage: 40

  roles:
    - role: common
      tags:
        - common
    
    - role: docker
      tags:
        - docker

    # - role: k3s
    #   tags:
    #     - k3s

    # - role: metallb
    #   tags:
    #     - metallb

    # - role: adguard
    #   tags:
    #     - adguard

    # - role: plex
    #   tags:
    #     - plex

    # - role: qbittorrent
    #   tags:
    #     - qbittorrent

# - name: Configure K3s
#   hosts: k3s
#   become: true

#   roles:
#     - k3s
