---
- name: Configure all servers
  hosts: all
  become: true

  roles:
    - role: common
      tags:
        - common

    # - role: k3s
    #   tags:
    #     - k3s

    # - role: metallb
    #   tags:
    #     - metallb

    # - role: adguard
    #   tags:
    #     - adguard

    # - role: plex
    #   tags:
    #     - plex

    # - role: qbittorrent
    #   tags:
    #     - qbittorrent

# - name: Configure K3s
#   hosts: k3s
#   become: true

#   roles:
#     - k3s
